config/routes.rb
WorkingWithBase::Application.routes.draw do
  
  resources :users

  root :to => 'processing#index'

  get "processing/index", :as => "index";

  get "processing/new_record", :as => "new_record";

  get "processing/extract_record", :as => "read_record";

  match ':controller(/:action(/:id(.:format)))'
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, :presence =>true
	validates :description, :presence =>true
	validates :owner, :presence =>true
	validates :holder, :presence =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/processing_controller.rb
class ProcessingController < ApplicationController
  def index
	@title = "Главная страница"
	@item=Item.all
  end

  def new_record
	@title = "Создание новой записи о предмете"
	@item=Item.new
  end
  
  def create_record
	@item=Item.new(params[:item])
	if @item.save
	  redirect_to root_url, :notice => "Запись в базу данных выполнена."
	else
	  redirect_to root_url, :notice => "Ошибка записи в базу данных."
	end
  end

  def extract_record
	@title = "Показать запись"
	@item=Item.find(1)
  end

  def show_record
	@item=Item.find(params[:item][:id])
	redirect_to root_url, :notice => "#{@item.name} #{@item.description} #{@item.owner} #{@item.holder}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/processing_helper.rb
module ProcessingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= @title %> </title>
  <%= stylesheet_link_tag("styles1", :media => 'screen')%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render('layouts/header')%> 	<!отображение партиала _header.html.erb>
  <%= yield %>
  
</body>
</html>

app/views/processing/extract_record.html.erb
<div id='content'>
	<h2>Прочитать запись из БД</h2>
	<%= form_for(@item, :url => {:action => "show_record"}) do |f|%>
	<table><tr><td>Введите номер записи</td>	
	           <td><%= f.text_field :id, :size=>10 %> </td></tr>
	<tr><td><%= f.submit ("Показать запись")%></td></tr></table>
	<% end %>
</div>

app/views/processing/index.html.erb
<div id='content'>
	<div id='notice'><%= flash[:notice]%><div>

	<table> <tr> 
		<td> <div id='link'>
	<%= link_to 'Новая запись', new_record_path %> </div> </td> 
	<td> <div id='link'>
	<%= link_to 'Прочитать запись из БД', read_record_path %> </div> </td> </tr> 
	</table>
</div>

app/views/processing/new_record.html.erb
<div id='content'>
	<h2>Создать запись о новом предмете</h2>
      
	<%= form_for(@item, :url => {:action => "create_record"}) do |f|%>
	<table><tr><td>Название</td>	
	           <td><%= f.text_field :name, :size=>30 %> </td></tr>
	<tr><td>Описание</td>
	    <td><%= f.text_field :description, :size=>30 %> </td></tr>
	<tr><td>Владелец</td>
	    <td><%= f.text_field :owner, :size=>30 %> </td></tr>
	<tr><td>Держатель</td>
	    <td><%= f.text_field :holder, :size=>30 %> </td></tr>
	<tr><td><%= f.submit ("Создать запись")%></td></tr></table>
	<% end %>
</div>